### ISSUE TITLE
chmod()のところでエラーが発生しました。

### ISSUE THREAD

**Issue by Takesikaityo** [kametan0730MC/SkinUploader#1]
https://plus.google.com/105250560911974727147/posts/Y1tqNmkLpu3
恐らく、権限関係のものだと思います。((winなら大丈夫かな？
環境 android 5.1 64bit 
RAM 2GB
ROM 16GB

**Comment by kametan0730** [comment]
ぼくはだいじょうぶだったんだがなぁ、報告ありがとう！

**Comment by Takesikaityo** [comment]
winですか？

**Comment by Takesikaityo** [comment]
https://plus.google.com/105250560911974727147/posts/Wx9hT1sC3ow
権限系消したら問題なしでした

**Comment by kametan0730** [comment]
winでもlinuxでも

**Comment by Takesikaityo** [comment]
androidはcommandline系の制限が厳しいからね。 shすら使えない
たぶん、androidでweb鯖を建てる人はあまりいないから大丈夫だとおもう。

**Comment by kametan0730** [comment]
ok

**Comment by kametan0730** [comment]
権限ないとwebからアップロードされた写真見れちゃうんだよね

**Comment by Takesikaityo** [comment]
そりゃ見えてしまうからね。でも、なんかのmodやplugin uploaderなら見れないと逆に困る
